# Generated by Django 5.2 on 2025-05-07 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_verificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="subscriptions",
            field=models.ManyToManyField(
                blank=True, related_name="subscribers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
