# Generated by Django 5.2 on 2025-05-17 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_customuser_subscriptions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="subscriptions",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("muted", "Muted"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("notify", models.BooleanField(default=True)),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
                "indexes": [
                    models.Index(
                        fields=["subscriber", "status"],
                        name="account_sub_subscri_deadcc_idx",
                    ),
                    models.Index(
                        fields=["target_user", "status"],
                        name="account_sub_target__40db45_idx",
                    ),
                ],
                "unique_together": {("subscriber", "target_user")},
            },
        ),
    ]
